### ISSUE TITLE
group professions

### ISSUE THREAD

**Issue by mattflaherty97** [mattflaherty97/case-2-team-3#18]
group professions to to get a better understanding of defaulting among fewer professions

**Comment by Jiayif** [comment]
Need revise:

science: Microbiologist, Technician, Technology_specialist, Technical_writer, Scientist, Statistician, Geologist
engineering: Mechanical_engineer, Civil_engineer, Petroleum_Engineer, Software_Developer, Biomedical_Engineer, Computer_hardware_engineer', Computer_operator, Chemical_engineer,Industrial_Engineer', Engineer, Web_designer
social and cultural: Flight_attendant, Air_traffic_controller, Firefighter, Army_officer, Civil_servant, Librarian, Official, Comedian,Drafter, Politician, Secretary, Magistrate, Psychologist,Lawyer
art: Graphic_Designer, Designer,Design_Engineer, Fashion_Designer
Business: Economist, Hotel_Manager, Consultant, Chartered_Accountant, Analyst
Professional: Architect', Aviator, Chef,'Physician, Dentist, Surgeon
